version: "3.9"
services:
  dn-web:
    container_name: dn-web
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/data:/data:ro
      - ./nginx/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
    restart: unless-stopped
    networks:
      dnnet:
        ipv4_address: 172.18.0.10

  mqtt-broker:
    container_name: mqtt-broker
    build:
      context: ./mosquitto
      network: host
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/responder.py:/usr/local/bin/responder.py:ro
    restart: unless-stopped
    networks:
      dnnet:
        ipv4_address: 172.18.0.20

  dns-responder:
    container_name: dns-responder
    build:
      context: ./dns_simple
      network: host
    restart: unless-stopped
    ports:
      - "5353:53/udp"
    volumes:
      - ./dns_simple/hosts.txt:/app/hosts.txt:rw
    networks:
      dnnet:
        ipv4_address: 172.18.0.30

networks:
  dnnet:
    name: dnnet
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
